import os
import html
import requests
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_cors import CORS

load_dotenv()

app = Flask(__name__)

# ------------------------------------------------------------
# CORS
# ------------------------------------------------------------
# Keep this open for the portfolio frontend.
# You can restrict this to your exact portfolio domain later.
CORS(app, resources={r"/api/*": {"origins": "*"}})


# ------------------------------------------------------------
# ENVIRONMENT
# ------------------------------------------------------------
BREVO_API_KEY = os.getenv("BREVO_API_KEY", "").strip()
EMAIL_USERNAME = os.getenv("EMAIL_USERNAME", "").strip()
EMAIL_FROM_NAME = os.getenv("EMAIL_FROM_NAME", "Shahab Sanowar").strip()
OWNER_EMAIL = os.getenv("OWNER_EMAIL", EMAIL_USERNAME).strip()

REQUIRED_FIELDS = ("name", "email", "service")


# ------------------------------------------------------------
# HELPERS
# ------------------------------------------------------------
def esc(value):
    """Safely escape user-provided values before putting them in HTML."""
    return html.escape(str(value or ""), quote=True)


def text_to_html(text):
    """Simple text fallback for the email's plain-text message."""
    return html.escape(str(text or "")).replace("\n", "<br>")


def email_shell(preheader, content_html):
    """
    Shared premium email shell matching the portfolio:
    black background + dark cards + cyan accent.
    Uses table layout for email-client compatibility.
    """
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shahab Sanowar</title>
</head>
<body style="margin:0;padding:0;background:#05070a;color:#e8edf7;font-family:Arial,Helvetica,sans-serif;">
    <div style="display:none;max-height:0;overflow:hidden;opacity:0;">
        {esc(preheader)}
    </div>

    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"
           style="width:100%;background:#05070a;margin:0;padding:0;">
        <tr>
            <td align="center" style="padding:34px 14px;">

                <table role="presentation" width="620" cellspacing="0" cellpadding="0" border="0"
                       style="width:100%;max-width:620px;background:#0b0d12;border:1px solid #20283a;border-radius:16px;overflow:hidden;">

                    <!-- Header -->
                    <tr>
                        <td style="padding:22px 28px;background:#0f1219;border-bottom:1px solid #20283a;">
                            <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0">
                                <tr>
                                    <td style="font-size:20px;font-weight:800;letter-spacing:-0.4px;color:#ffffff;">
                                        Md Shahab <span style="color:#16e3c2;">Sanowar</span>
                                    </td>
                                    <td align="right" style="font-size:11px;color:#78819b;font-family:monospace;white-space:nowrap;">
                                        portfolio.contact
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <!-- Accent line -->
                    <tr>
                        <td style="height:2px;background:#16e3c2;font-size:0;line-height:0;">
                            &nbsp;
                        </td>
                    </tr>

                    <!-- Content -->
                    <tr>
                        <td style="padding:32px 28px 28px;">
                            {content_html}
                        </td>
                    </tr>

                    <!-- Footer -->
                    <tr>
                        <td style="padding:20px 28px;background:#080a0e;border-top:1px solid #1b2230;">
                            <div style="font-size:12px;color:#65738c;line-height:1.7;">
                                <strong style="color:#aeb7c6;">Md Shahab Sanowar</strong><br>
                                Backend Developer · Python &amp; Django
                            </div>
                            <div style="margin-top:10px;font-size:11px;color:#4f596c;">
                                This email was generated by the contact system of Shahab Sanowar's portfolio.
                            </div>
                        </td>
                    </tr>

                </table>

            </td>
        </tr>
    </table>
</body>
</html>"""


def build_owner_email(name, visitor_email, service, message, submitted_at):
    """HTML email sent to Shahab when someone contacts the portfolio."""
    safe_name = esc(name)
    safe_email = esc(visitor_email)
    safe_service = esc(service)
    safe_message = text_to_html(message)
    safe_time = esc(submitted_at)

    content = f"""
        <div style="font-size:11px;font-weight:700;letter-spacing:1.6px;color:#16e3c2;text-transform:uppercase;">
            New Portfolio Enquiry
        </div>

        <h1 style="margin:10px 0 8px;color:#ffffff;font-size:30px;line-height:1.15;letter-spacing:-1px;">
            Someone wants to work with you.
        </h1>

        <p style="margin:0 0 26px;color:#8e98aa;font-size:14px;line-height:1.7;">
            A new message has been submitted through your portfolio contact form.
        </p>

        <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"
               style="background:#10141c;border:1px solid #222b3b;border-radius:12px;">
            <tr>
                <td style="padding:20px 22px;">
                    <div style="font-size:10px;color:#65738c;letter-spacing:1.3px;font-weight:700;">
                        CONTACT DETAILS
                    </div>

                    <div style="margin-top:15px;font-size:14px;line-height:1.9;color:#dce2ec;">
                        <strong style="color:#ffffff;">Name</strong><br>
                        {safe_name}
                        <br><br>

                        <strong style="color:#ffffff;">Email</strong><br>
                        <a href="mailto:{safe_email}" style="color:#16e3c2;text-decoration:none;">
                            {safe_email}
                        </a>
                        <br><br>

                        <strong style="color:#ffffff;">Service Needed</strong><br>
                        <span style="display:inline-block;margin-top:4px;padding:7px 10px;border:1px solid #23483f;border-radius:7px;color:#16e3c2;background:#0b1715;">
                            {safe_service}
                        </span>
                        <br><br>

                        <strong style="color:#ffffff;">Submitted</strong><br>
                        {safe_time}
                    </div>
                </td>
            </tr>
        </table>

        <div style="margin-top:22px;font-size:10px;color:#65738c;letter-spacing:1.3px;font-weight:700;">
            MESSAGE
        </div>

        <div style="margin-top:10px;padding:18px 20px;background:#080b10;border-left:3px solid #16e3c2;border-radius:8px;color:#cbd3df;font-size:14px;line-height:1.75;">
            {safe_message or '<span style="color:#65738c;">No message was provided.</span>'}
        </div>

        <div style="margin-top:24px;">
            <a href="mailto:{safe_email}?subject=Re:%20Portfolio%20Enquiry"
               style="display:inline-block;padding:12px 18px;background:#16e3c2;color:#06100e;text-decoration:none;font-size:13px;font-weight:800;border-radius:8px;">
                Reply to {safe_name}
            </a>
        </div>
    """

    return email_shell(
        f"New portfolio enquiry from {name} — {service}",
        content
    )


def build_visitor_email(name, service):
    """HTML confirmation email sent to the person who submitted the form."""
    safe_name = esc(name)
    safe_service = esc(service)

    content = f"""
        <div style="display:inline-block;padding:7px 10px;border:1px solid #23483f;border-radius:7px;color:#16e3c2;background:#0b1715;font-size:10px;font-weight:700;letter-spacing:1.1px;text-transform:uppercase;">
            Message Received
        </div>

        <h1 style="margin:18px 0 10px;color:#ffffff;font-size:30px;line-height:1.15;letter-spacing:-1px;">
            Thanks for reaching out, {safe_name}.
        </h1>

        <p style="margin:0;color:#aeb7c6;font-size:15px;line-height:1.8;">
            I've received your message through my portfolio and will review the details carefully.
        </p>

        <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"
               style="margin-top:24px;background:#10141c;border:1px solid #222b3b;border-radius:12px;">
            <tr>
                <td style="padding:20px 22px;">
                    <div style="font-size:10px;color:#65738c;letter-spacing:1.3px;font-weight:700;">
                        YOUR REQUEST
                    </div>
                    <div style="margin-top:10px;color:#ffffff;font-size:17px;font-weight:700;">
                        {safe_service}
                    </div>
                    <div style="margin-top:7px;color:#78819b;font-size:12px;line-height:1.6;">
                        Your enquiry has been successfully received.
                    </div>
                </td>
            </tr>
        </table>

        <p style="margin:24px 0 0;color:#8e98aa;font-size:14px;line-height:1.8;">
            I'll get back to you as soon as possible. If you need to add anything,
            you can simply reply to this email.
        </p>

        <div style="margin-top:28px;padding-top:20px;border-top:1px solid #20283a;">
            <div style="color:#ffffff;font-size:14px;font-weight:700;">
                Best regards,
            </div>
            <div style="margin-top:4px;color:#16e3c2;font-size:14px;font-weight:700;">
                Md Shahab Sanowar
            </div>
            <div style="margin-top:3px;color:#65738c;font-size:12px;">
                Backend Developer · Python &amp; Django
            </div>
        </div>
    """

    return email_shell(
        "Your message to Md Shahab Sanowar has been received.",
        content
    )


def send_email(to_email, subject, text_body, html_body, reply_to=None):
    """Send one email through Brevo."""
    if not BREVO_API_KEY or not EMAIL_USERNAME:
        raise RuntimeError(
            "Brevo email configuration is missing"
        )

    payload = {
        "sender": {
            "name": EMAIL_FROM_NAME,
            "email": EMAIL_USERNAME,
        },
        "to": [
            {
                "email": to_email
            }
        ],
        "subject": subject,
        "textContent": text_body,
        "htmlContent": html_body,
    }

    if reply_to:
        payload["replyTo"] = {
            "email": reply_to
        }

    response = requests.post(
        "https://api.brevo.com/v3/smtp/email",
        headers={
            "accept": "application/json",
            "api-key": BREVO_API_KEY,
            "content-type": "application/json",
        },
        json=payload,
        timeout=30,
    )

    if not response.ok:
        raise RuntimeError(
            f"Brevo API error {response.status_code}: "
            f"{response.text[:500]}"
        )

    return response.json() if response.content else {}


# ------------------------------------------------------------
# HEALTH CHECK
# ------------------------------------------------------------
@app.get("/api/health")
def health():
    return jsonify({
        "ok": True,
        "service": "portfolio-contact-api"
    })


# ------------------------------------------------------------
# CONTACT API
# ------------------------------------------------------------
@app.post("/api/contact")
def contact():
    data = request.get_json(silent=True) or {}

    name = str(data.get("name", "")).strip()
    visitor_email = str(data.get("email", "")).strip()
    service = str(data.get("service", "")).strip()
    message = str(data.get("message", "")).strip()

    # Required fields
    missing = [
        field
        for field in REQUIRED_FIELDS
        if not str(data.get(field, "")).strip()
    ]

    if missing:
        return jsonify({
            "ok": False,
            "message": "Please fill all required fields."
        }), 400

    # Length protection
    if (
        len(name) > 120
        or len(visitor_email) > 254
        or len(service) > 120
        or len(message) > 5000
    ):
        return jsonify({
            "ok": False,
            "message": "One or more fields are too long."
        }), 400

    # Basic email validation
    if "@" not in visitor_email or "." not in visitor_email.split("@")[-1]:
        return jsonify({
            "ok": False,
            "message": "Please enter a valid email address."
        }), 400

    submitted_at = datetime.now(timezone.utc).astimezone().strftime(
        "%d %b %Y, %I:%M %p"
    )

    # --------------------------------------------------------
    # OWNER EMAIL
    # --------------------------------------------------------
    owner_subject = f"New Portfolio Contact — {name}"

    owner_text = f"""Hello Shahab,

Someone has contacted you through your portfolio website.

CONTACT DETAILS
----------------
Name: {name}
Email: {visitor_email}
Service Needed: {service}
Submitted: {submitted_at}

MESSAGE
----------------
{message}

You can reply directly to this email to respond to {name}.

— Portfolio Contact System
"""

    owner_html = build_owner_email(
        name=name,
        visitor_email=visitor_email,
        service=service,
        message=message,
        submitted_at=submitted_at,
    )

    # --------------------------------------------------------
    # VISITOR CONFIRMATION EMAIL
    # --------------------------------------------------------
    visitor_subject = "Thank You for Reaching Out — Shahab Sanowar"

    visitor_text = f"""Hi {name},

Thank you for reaching out through my portfolio website.

I've received your message regarding "{service}" and will review the details carefully. I'll get back to you as soon as possible.

I appreciate you taking the time to share your idea with me.

Best regards,
Shahab Sanowar
Backend Developer | Python & Django
"""

    visitor_html = build_visitor_email(
        name=name,
        service=service,
    )

    # --------------------------------------------------------
    # SEND BOTH
    # --------------------------------------------------------
    try:
        # 1. Send enquiry to Shahab
        send_email(
            OWNER_EMAIL,
            owner_subject,
            owner_text,
            owner_html,
            reply_to=visitor_email,
        )

        # 2. Send confirmation to visitor
        send_email(
            visitor_email,
            visitor_subject,
            visitor_text,
            visitor_html,
        )

        return jsonify({
            "ok": True,
            "message": "Message sent successfully. Thank you!"
        })

    except Exception as exc:
        # Keep credentials/internal details out of the browser.
        app.logger.exception(
            "Portfolio contact email failed: %s",
            exc
        )

        return jsonify({
            "ok": False,
            "message": "Unable to send your message right now. Please try again."
        }), 500


# ------------------------------------------------------------
# RUN
# ------------------------------------------------------------
if __name__ == "__main__":
    port = int(os.getenv("PORT", "5000"))
    app.run(
        host="0.0.0.0",
        port=port,
        debug=False
    )
